package(default_visibility = ["//visibility:public"])

licenses(["notice"])

filegroup(
    name = "license",
    srcs = ["COPYING"],
)

cc_library(
    name = "base",
    srcs = [
"strings/ascii_ctype.cc",
"strings/split.cc",
"strings/stringprintf.cc",
"strings/strutil.cc",
"util/coding/coder.cc",
"util/coding/varint.cc",
"util/hash/hash.cc",
"util/math/exactfloat/exactfloat.cc",
"util/math/mathlimits.cc",
"util/math/mathutil.cc",
"base/int128.cc",
"base/logging.cc",
"base/stringprintf.cc",
"base/strtoint.cc",
    ],
    hdrs = [
"util/coding/varint.h",
"util/endian/endian.h",
"util/hash/hash_jenkins_lookup2.h",
"strings/split.h",
"strings/ascii_ctype.h",
"strings/stringprintf.h",
"strings/strutil.h",
"util/coding/coder.h",
"base/int128.h",
"base/integral_types.h",
"base/strtoint.h",
"base/template_util.h",
"base/type_traits.h",       
"base/stringprintf.h",
"base/logging.h",
"base/macros.h",
"base/port.h",
"base/scoped_ptr.h",
"util/math/exactfloat/exactfloat.h",
"util/math/mathlimits.h",
"util/math/mathutil.h",
"util/math/matrix3x3-inl.h",
"util/math/matrix3x3.h",
"util/math/vector2-inl.h",
"util/math/vector2.h",
"util/math/vector3-inl.h",
"util/math/vector3.h",
"util/math/vector4-inl.h",
"util/math/vector4.h",
"base/basictypes.h",
"base/casts.h",
"base/commandlineflags.h",
    ],
    copts = [
        "-Wall",
        "-Wwrite-strings",
        "-Woverloaded-virtual",
        "-Wno-sign-compare",
        "-Wno-deprecated", # included hash_map
        "-DS2_USE_EXACTFLOAT",
        "-DHASH_NAMESPACE=std",
        "-Wno-narrowing",
        "-std=c++11",
    ],
    linkopts = [
        "-lssl",
        "-lcrypto",
    ],
)

cc_library(
    name = "s2",
    srcs = [
"s1angle.cc",
"s1interval.cc",
"s2.cc",
"s2cap.cc",
"s2cell.cc",
"s2cellid.cc",
"s2cellunion.cc",
"s2edgeindex.cc",
"s2edgeutil.cc",
"s2latlng.cc",
"s2latlngrect.cc",
"s2loop.cc",
"s2pointregion.cc",
"s2polygon.cc",
"s2polygonbuilder.cc",
"s2polyline.cc",
"s2r2rect.cc",
"s2region.cc",
"s2regioncoverer.cc",
"s2regionintersection.cc",
"s2regionunion.cc",
    ],
    hdrs = [
"s2/r1interval.h",
"s2/s1angle.h",
"s2/s1interval.h",
"s2/s2.h",
"s2/s2cap.h",
"s2/s2cell.h",
"s2/s2cellid.h",
"s2/s2cellunion.h",
"s2/s2edgeindex.h",
"s2/s2edgeutil.h",
"s2/s2latlng.h",
"s2/s2latlngrect.h",
"s2/s2loop.h",
"s2/s2pointregion.h",
"s2/s2polygon.h",
"s2/s2polygonbuilder.h",
"s2/s2polyline.h",
"s2/s2r2rect.h",
"s2/s2region.h",
"s2/s2regioncoverer.h",
"s2/s2regionintersection.h",
"s2/s2regionunion.h",
    ], 
    copts = [
        "-Wall",
        "-Wwrite-strings",
        "-Woverloaded-virtual",
        "-Wno-sign-compare",
        "-Wno-deprecated", # included hash_map
        "-DS2_USE_EXACTFLOAT",
        "-DHASH_NAMESPACE=std",
        "-std=c++11",
    ],
    deps = [ ":base" ],
)

